graph TD
    Lisp[Lisp 1.5<br>1958] --> CommonLisp[Common Lisp<br>1984]
    Lisp --> Scheme[Scheme<br>1975]
    Lisp --> InterLisp[InterLisp<br>1967]
    Lisp --> MacLisp[MacLisp<br>1966]
    
    MacLisp --> ZetaLisp[ZetaLisp<br>1978]
    MacLisp --> CommonLisp
    ZetaLisp --> CommonLisp
    
    Scheme --> Racket[Racket<br>1995]
    CommonLisp --> EmacLisp[Emacs Lisp<br>1985]
    
    Scheme --> Clojure[Clojure<br>2007]
    
    Clojure --> Hy[Hy<br>2013]
    
    Lisp --> NewLisp[NewLisp<br>1991]
    Lisp --> Fennel[Fennel<br>2016]
    Lisp --> Janet[Janet<br>2017]
    
    style Lisp fill:#f9f,stroke:#333,stroke-width:4px
    style CommonLisp fill:#bbf,stroke:#333,stroke-width:4px
    style Scheme fill:#bfb,stroke:#333,stroke-width:4px
    style Clojure fill:#bbf,stroke:#333,stroke-width:3px
    style Racket fill:#fbf,stroke:#333,stroke-width:3px
    style EmacLisp fill:#fbf,stroke:#333,stroke-width:3px
    style Hy fill:#fbb,stroke:#333,stroke-width:2px
    style Fennel fill:#bff,stroke:#333,stroke-width:2px
    style Janet fill:#ffb,stroke:#333,stroke-width:2px
